document.addEventListener("DOMContentLoaded", function () {
    const phrases = [
        "Eres la razón de mis sonrisas.",
        "Contigo cada día es un regalo.",
        "Mi mundo es perfecto porque estás en él.",
        "Tu amor es mi mayor tesoro.",
        "Siempre te amaré, hoy y siempre.",
        "Tu amor ilumina mis días.",
        "Eres mi sol en un día nublado.",
        "Eres mi mejor historia de amor.",
        "Todo es más bello contigo a mi lado.",
        "Tu amor es la melodía de mi corazón.",
        "Mi amor por ti crece cada día.",
        "Eres mi primer pensamiento al despertar.",
        "Te amo más allá de las palabras.",
        "Eres mi refugio y mi hogar.",
        "Eres el sueño del que no quiero despertar.",
        "Tú y yo somos el mejor equipo.",
        "Eres la estrella que guía mi camino.",
        "Tu amor es mi inspiración.",
        "Eres mi felicidad eterna.",
        "Contigo el tiempo se detiene.",
        "Eres mi ángel, mi amor, mi vida.",
        "No hay palabras para describir cuánto te amo.",
        "Eres mi todo, mi universo.",
        "Cada día me enamoro más de ti.",
        "Eres la respuesta a mis oraciones.",
        "Te amo más de lo que imaginas.",
        "Eres mi felicidad constante.",
        "El amor que siento por ti es infinito.",
        "Eres la pieza que completa mi vida.",
        "Eres mi dulce escape de la realidad.",
        "No importa el lugar, siempre es mejor contigo.",
        "Eres mi poesía favorita.",
        "Mi amor por ti no conoce límites.",
        "Cada día contigo es una bendición.",
        "Eres mi amor eterno.",
        "Eres mi para siempre.",
        "Te amo por lo que eres.",
        "Mi vida no sería la misma sin ti.",
        "Eres el motivo de mi alegría.",
        "No hay nadie como tú.",
        "Eres la razón por la que sonrío.",
        "Te amo más cada día.",
        "Eres mi sol y mi luna.",
        "Mi amor por ti es inmenso.",
        "Eres la persona que siempre soñé.",
        "Eres mi tesoro más preciado.",
        "Eres la mejor parte de mi vida.",
        "Te amo más de lo que las palabras pueden decir.",
        "Eres mi milagro.",
        "Mi amor por ti es inagotable.",
        "Eres el centro de mi universo.",
        "Eres mi amor verdadero.",
        "Eres mi razón de ser.",
        "Te amo con todo mi corazón.",
        "Eres la luz en mi vida.",
        "Eres el amor de mi vida.",
        "Mi corazón es tuyo.",
        "Eres mi destino.",
        "Te amo más de lo que puedes imaginar.",
        "Eres mi mejor amigo y mi amor.",
        "Eres mi razón de vivir.",
        "Eres todo lo que necesito.",
        "Cada momento contigo es un sueño hecho realidad.",
        "Eres mi mundo entero.",
        "Tu risa es mi melodía favorita.",
        "Eres el latido de mi corazón.",
        "Cada día a tu lado es una bendición.",
        "Eres el sueño que nunca quiero dejar.",
        "Eres mi pasión y mi vida.",
        "Tu amor me llena de alegría.",
        "Eres la razón de mi felicidad.",
        "Tu presencia es todo lo que necesito.",
        "Eres mi inspiración diaria.",
        "Eres el anhelo de mi alma.",
        "Tu amor es mi mayor tesoro.",
        "Eres mi pensamiento constante.",
        "Tu ternura me hace sonreír.",
        "Eres el centro de mis pensamientos.",
        "Eres mi lugar feliz.",
        "Tu amor me hace sentir completo.",
        "Eres la razón de mi existencia.",
        "Cada día contigo es una aventura.",
        "Tu amor es mi mayor regalo.",
        "Eres la calma en mis tormentas.",
        "Eres el sueño que nunca quiero despertar.",
        "Tu amor es mi refugio.",
        "Eres mi alegría diaria.",
        "Cada beso tuyo es un sueño hecho realidad.",
        "Eres mi cielo estrellado.",
        "Tu amor ilumina mi vida.",
        "Eres la fuerza que me motiva.",
        "Eres mi felicidad sin fin.",
        "Tu amor es mi mayor fortaleza.",
        "Eres mi sueño hecho realidad.",
        "Cada día contigo es un nuevo comienzo.",
        "Eres la razón de mi sonrisa constante.",
        "Tu amor es mi mayor tesoro.",
        "Eres mi todo, mi razón de ser.",
        "Eres la fuente de mi felicidad.",
        "Tu amor es la luz de mi vida.",
        "Eres mi inspiración eterna.",
        "Cada momento contigo es especial.",
        "Eres mi amor infinito.",
        "Tu amor es mi mayor alegría.",
        "Eres el sueño de mi vida.",
        "Cada día contigo es un regalo.",
        "Eres mi mayor bendición.",
        "Tu amor es mi mayor tesoro.",
        "Eres el sol en mi cielo.",
        "Cada segundo contigo es perfecto.",
        "Eres mi sueño y mi realidad.",
        "Tu amor me hace sentir completo.",
        "Eres mi anhelo eterno.",
        "Cada instante contigo es invaluable.",
        "Eres la razón de mi felicidad diaria.",
        "Tu amor es mi fuerza vital.",
        "Eres mi felicidad constante.",
        "Cada día contigo es un sueño hecho realidad.",
        "Eres la luz en mi oscuridad.",
        "Tu amor es mi mayor regalo.",
        "Eres mi esperanza y mi vida.",
        "Cada momento contigo es un tesoro.",
        "Eres mi amor eterno y verdadero.",
        "Tu amor es mi mayor alegría.",
        "Eres el latido de mi corazón.",
        "Cada día contigo es una bendición.",
        "Eres mi sol en días grises.",
        "Tu amor me hace sentir completo.",
        "Eres mi paz y mi felicidad.",
        "Cada beso tuyo es un sueño.",
        "Eres mi todo y mi siempre.",
        "Tu amor es mi mayor fortaleza.",
        "Eres la razón de mi vida.",
        "Cada momento contigo es perfecto.",
        "Eres mi sueño y mi realidad.",
        "Tu amor es mi mayor alegría.",
        "Eres mi felicidad eterna.",
        "Cada día contigo es un regalo.",
        "Eres la luz que ilumina mi camino.",
        "Tu amor es mi mayor tesoro.",
        "Eres mi amor infinito y eterno."
    ];

    const images = [
        "imagenes/amor1.gif",
        "imagenes/amor2.gif",
        "imagenes/amor3.gif",
        "imagenes/amor4.gif",
        "imagenes/amor5.gif",
        "imagenes/amor6.gif",
        "imagenes/amor7.gif",
        "imagenes/amor8.gif",
        "imagenes/amor9.gif",
        "imagenes/amor10.gif",
        "imagenes/amor11.gif",
        "imagenes/amor12.gif",
        "imagenes/amor13.gif",
        "imagenes/amor14.gif",
        "imagenes/amor15.gif",
        "imagenes/amor16.gif",
        "imagenes/amor17.gif",
        "imagenes/amor18.gif",
        "imagenes/amor19.gif",
        "imagenes/amor20.gif",
        "imagenes/amor21.gif",
        "imagenes/amor22.gif",
        "imagenes/amor23.gif",
        "imagenes/amor24.gif",
        "imagenes/amor25.gif"
    ];
    // Recuperar el contador del almacenamiento local, o inicializar a 0 si no existe
    let currentImageIndex = parseInt(localStorage.getItem("currentImageIndex"), 10) || 0;

    // Seleccionar una frase aleatoria
    const randomPhraseIndex = Math.floor(Math.random() * phrases.length);
    const selectedPhrase = phrases[randomPhraseIndex];

    // Cambiar la frase y la imagen
    document.getElementById("love-phrase").textContent = selectedPhrase;
    document.getElementById("love-image").src = images[currentImageIndex];

    // Incrementar el índice de la imagen y hacer que vuelva al inicio si supera el límite
    currentImageIndex = (currentImageIndex + 1) % images.length;

    // Guardar el nuevo índice en el almacenamiento local
    localStorage.setItem("currentImageIndex", currentImageIndex);

    // Manejo de errores de imagen
    document.getElementById("love-image").onerror = function () {
        console.error(`No se pudo cargar la imagen: ${images[currentImageIndex]}`);
        document.getElementById("love-image").src = "imagenes/default.gif"; // Imagen por defecto
    };
});